version: '3.8'

services:
  datascience:
    container_name: datascience-wscontainer
    restart: unless-stopped
    build:
      args:
        - NODE_VERSION=node
        - USERNAME=codespace
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    user: codespace
    init: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              driver: nvidia
              count: all
